name: A Build for Android TEST

on:
  push:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name:
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        version: '5.15.2'
    - name: Setup NDK path
      shell: bash
      run: echo "ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
    - name: qmake apk
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        qmake
        make -j12
        make apk
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.90.0"
        prerelease: true
        title: "PreRelease"
        files: |
          android-build/build/outputs/apk/debug/android-build-debug.apk
       
