name: A Build for Android TEST

on:
  push:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Actions Runner-Image 5879
      run: |
        function get_full_ndk_version {
            majorVersion=$1
            ndkFullVersion=$($SDKMANAGER --list | grep "ndk;${majorVersion}.*" | awk '{gsub("ndk;", ""); print $1}' | sort -V | tail -n1)
            echo "$ndkFullVersion"
        }
        ANDROID_ROOT=/usr/local/lib/android
        ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
        ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
        SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
        ndkDefaultFullVersion=$(get_full_ndk_version "23")
        ln -sf $ANDROID_SDK_ROOT/ndk/$ndkDefaultFullVersion $ANDROID_NDK_ROOT

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        version: '5.15.2'
    - name: Setup NDK path
      shell: bash
      run: echo "ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: qmake apk
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        qmake
        make -j12
        make apk
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.90.0"
        prerelease: true
        title: "PreRelease"
        files: |
          android-build/build/outputs/apk/debug/android-build-debug.apk
       
