name: A Build for Android TEST

on:
  push:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Actions Runner-Image 5879
      run: |
         $sdkRoot = "C:\Android\android-sdk"
         $sdkManager = "$sdkRoot\cmdline-tools\latest\bin\sdkmanager.bat"
         $androidPackages = Get-AndroidPackages -AndroidSDKManagerPath $sdkManager
         $ndkDefaultVersion = ($androidPackages | Where-Object { $_ -match "ndk;23" }).Split(';')[1]
         $ndkRoot = "$sdkRoot\ndk-bundle"
         New-Item -Path $ndkRoot -ItemType SymbolicLink -Value "$sdkRoot\ndk\$ndkDefaultVersion"
         setx ANDROID_NDK_HOME $ndkRoot /M
         setx ANDROID_NDK_PATH $ndkRoot /M
         setx ANDROID_NDK_ROOT $ndkRoot /M
         (Get-Content -Encoding UTF8 "${ndkRoot}\ndk-build.cmd").replace('%~dp0\build\ndk-build.cmd','"%~dp0\build\ndk-build.cmd"')|Set-Content -Encoding UTF8 "${ndkRoot}\ndk-build.cmd"
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        version: '5.15.2'
    - name: Setup NDK path
      shell: bash
      run: echo "ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: qmake apk
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        qmake
        make -j12
        make apk
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.90.0"
        prerelease: true
        title: "PreRelease"
        files: |
          android-build/build/outputs/apk/debug/android-build-debug.apk
       
