name: Build QtApp Android

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        version: '5.15.1'
        modules: 'qtcharts qtwebengine qtscript'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: move .so
      run: |
        cd android_project/stellarium
        ls -R
    - name: qmake apk
      run: |
        cd android_project/stellarium
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        qmake
        make
        make apk
    - name: show filetrees
      run: |
        ls -R
    - uses: actions/upload-artifact@v1
      if: github.event_name == 'push'
      with:
        name: Debug-APK
        path: android_project/stellarium/android-build//build/outputs/apk/debug/android-build-debug.apk
