name: DownUpLoad jom

on:
  workflow_dispatch:

jobs:
  GenerateWinStaticBinaries:
    runs-on: windows-2019

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Install jom
      run: |
        Invoke-WebRequest https://www.dropbox.com/s/dku543gtw7ik7hr/jom.zip?dl=1 -OutFile .\jom.zip
    - uses: actions/upload-artifact@v1
      with:
        name: jom.zip
        path: jom.zip

  
