name: Download Invoke-WebRequest

on:
  #push:
  workflow_dispatch:

jobs:

  #FetchIt1:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Wget Fetch
  #    run: |
  #      ls .
  #      wget https://web.archive.org/web/20010415000000/http://www.j-roen.net/diropener/castcopier100-800-1.zip
  #  - uses: actions/upload-artifact@v1
  #    with:
  #      name: artifacts
  #      path: ./

  FetchIt2:
    runs-on: windows-2019
    steps:
    - name: IW Fetch
      run: |
        ls .
        Invoke-WebRequest https://github.com/ytdl-org/youtube-dl/releases/download/2021.05.16/youtube-dl.exe -OutFile .\ydl.exe
        #Invoke-WebRequest https://web.archive.org/web/20140314141711/http://www.noctua-software.com/static/stellarium-mobile/stellarium-mobile-1.10.tar.gz -OutFile .\stellarium-mobile-1.10.tar.gz
        .\ydl.exe -u follow163@163.com -p 'lyg(8nsl' http://www.nicovideo.jp/watch/nm4318429
        ls .
    - uses: actions/upload-artifact@v1
      with:
        name: Art
        path: ./
