
#https://www.rasukarusan.com/entry/2018/12/03/002434

name: Stellarium Capture

on:
  # push:
  workflow_dispatch:

jobs:
  StellariumCapture:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Process
      run: |
        wget -q https://github.com/Stellarium/stellarium-data/releases/download/weekly-snapshot/Stellarium-0.20.3-3d1f6f2ae9-x86_64.AppImage
        # sudo apt-get uninstall xvfb -y
        sudo apt-get install xvfb -y
        Xvfb :10 -ac -screen 0 1024x768x24 & export DISPLAY=":10" 
        chmod +x ./Stellarium-0.20.3-3d1f6f2ae9-x86_64.AppImage && ./Stellarium-0.20.3-3d1f6f2ae9-x86_64.AppImage --headless  --screenshot-dir screenshots --startup-script $PWD/screencapture.ssc
        ls ~/Pictures/Stellarium -R
    - uses: actions/upload-artifact@v1
      with:
        name: Stellarium_Pics
        path: ~/Pictures/Stellarium/hosizora.png

